# Generated by Django 5.2.13 on 2026-04-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="banned_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="strike_count",
            field=models.IntegerField(default=0),
        ),
    ]
