# Generated by Django 5.2.13 on 2026-04-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="file_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="resource",
            name="minhash_signature",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="type",
            field=models.CharField(
                choices=[
                    ("SEMESTER", "Semester"),
                    ("TAHUN", "Tahun"),
                    ("KELAS", "Kelas"),
                    ("GENERAL", "General"),
                ],
                default="GENERAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("QUARANTINED", "Quarantined"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
