# Generated by Django 5.2.13 on 2026-05-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_resource_file_hash_resource_minhash_signature_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="resource",
            name="resources_r_search__82e125_gin",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="search_vector",
        ),
    ]
