# Generated by Django 5.2.13 on 2026-05-02 11:27

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_remove_resource_resources_r_search__82e125_gin_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="search_vector",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.CombinedSearchVector(
                        django.contrib.postgres.search.SearchVector(
                            "title", config="english", weight="A"
                        ),
                        "||",
                        django.contrib.postgres.search.SearchVector(
                            "description", config="english", weight="B"
                        ),
                        django.contrib.postgres.search.SearchConfig("english"),
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "markdown_body", config="english", weight="C"
                    ),
                    django.contrib.postgres.search.SearchConfig("english"),
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(
                    blank=True, null=True
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="resources_r_search__82e125_gin"
            ),
        ),
    ]
