name: Trigger auto deployment for tckr-backend-web

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tckr-backend-web-AutoDeployTrigger-a9eac3fa-d7a3-460b-a070-79539e27e333.yml'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TCKRBACKENDWEB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TCKRBACKENDWEB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TCKRBACKENDWEB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: tckrregistry.azurecr.io
          registryUsername: ${{ secrets.TCKRBACKENDWEB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TCKRBACKENDWEB_REGISTRY_PASSWORD }}
          containerAppName: tckr-backend-web
          resourceGroup: tckr
          imageToBuild: tckrregistry.azurecr.io/tckr-backend-web:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_

      - name: Deploy Worker to Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          registryUrl: tckrregistry.azurecr.io
          registryUsername: ${{ secrets.TCKRBACKENDWEB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TCKRBACKENDWEB_REGISTRY_PASSWORD }}
          containerAppName: tckr-celery-worker
          resourceGroup: tckr
          imageToDeploy: tckrregistry.azurecr.io/tckr-backend-web:${{ github.sha }}
